-- Script para atualizar apenas os capítulos 2-7 que não foram atualizados
-- Execute este script no Supabase SQL Editor

-- Atualizar capítulos 2-7 com conteúdo detalhado
-- Study ID: fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd

-- Capítulo 2: Lançando Sobre Ele Toda a Vossa Ansiedade
UPDATE bible_study_chapters 
SET reflective_reading = 'A ansiedade é uma emoção natural que todos experimentamos em diferentes momentos da vida. Ela pode se manifestar como preocupação excessiva, medo do futuro, ou sensação de que algo ruim vai acontecer. No entanto, a Bíblia nos ensina que não precisamos carregar esse peso sozinhos.\n\nPedro nos exorta a lançar toda a nossa ansiedade sobre Deus, porque Ele tem cuidado de nós. Esta é uma promessa poderosa que nos convida a confiar completamente no Senhor. Quando lançamos nossas preocupações sobre Ele, estamos reconhecendo que Ele é maior que nossos problemas e que tem o controle de todas as coisas.\n\nMas como podemos praticar isso no dia a dia? Primeiro, precisamos identificar o que está causando ansiedade em nossas vidas. Pode ser uma situação no trabalho, problemas financeiros, relacionamentos difíceis, ou preocupações com a saúde. Depois, devemos orar especificamente sobre essas questões, entregando-as a Deus com fé.\n\nÉ importante lembrar que "lançar" não significa simplesmente esquecer o problema, mas sim confiar que Deus vai cuidar dele da melhor forma. Isso nos liberta para focar no que realmente importa e viver com mais paz e serenidade.\n\nQuando sentimos ansiedade, podemos usar esta passagem como um lembrete de que Deus está sempre presente e pronto para nos ajudar. Ele não promete que não teremos problemas, mas promete estar conosco em meio a eles e nos dar a força necessária para enfrentá-los.\n\nA prática de lançar nossas ansiedades sobre Deus deve ser um hábito diário, não apenas algo que fazemos quando estamos desesperados. Quanto mais praticamos essa confiança, mais natural se torna e mais paz experimentamos em nossas vidas.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 2;

-- Capítulo 3: Buscai Primeiro o Reino de Deus
UPDATE bible_study_chapters 
SET reflective_reading = 'Jesus nos ensina uma lição fundamental sobre prioridades: devemos buscar primeiro o reino de Deus e a sua justiça. Esta é uma mudança radical na forma como vivemos nossas vidas, pois nos convida a colocar Deus em primeiro lugar em tudo o que fazemos.\n\nO que significa buscar o reino de Deus? Significa viver de acordo com os valores e princípios de Deus, priorizando o que é eterno sobre o que é temporal. Significa buscar a vontade de Deus em nossas decisões, relacionamentos e objetivos de vida.\n\nQuando buscamos primeiro o reino de Deus, todas as outras coisas são acrescentadas. Isso não significa que não teremos problemas ou dificuldades, mas que Deus vai cuidar de nossas necessidades de acordo com Sua sabedoria e tempo perfeitos.\n\nMuitas vezes, nossa ansiedade surge porque estamos focando nas coisas erradas. Preocupamo-nos com o que vamos comer, beber ou vestir, esquecendo que Deus já conhece nossas necessidades. Jesus nos lembra que até os pássaros do céu e os lírios do campo são cuidados por Deus, quanto mais nós, que somos muito mais valiosos para Ele.\n\nBuscar o reino de Deus também significa viver com propósito eterno. Em vez de nos preocuparmos apenas com o aqui e agora, devemos pensar no impacto que nossas ações têm na eternidade. Como estamos servindo a Deus e ao próximo? Como estamos crescendo em nossa fé e caráter?\n\nEsta mudança de foco nos ajuda a reduzir a ansiedade porque nos lembra que há algo maior e mais importante que nossas preocupações diárias. Quando Deus está em primeiro lugar, tudo o mais encontra seu lugar apropriado em nossas vidas.\n\nA promessa de Jesus é clara: quando buscamos primeiro o reino de Deus, Ele cuida de tudo o mais. Esta é uma promessa de provisão, proteção e paz para aqueles que confiam nEle.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 3;

-- Capítulo 4: A Paz de Deus que Excede Todo Entendimento
UPDATE bible_study_chapters 
SET reflective_reading = 'A paz de Deus é diferente de qualquer outra paz que o mundo pode oferecer. Ela excede todo entendimento porque não depende de circunstâncias externas, mas vem de um relacionamento profundo com Deus. Esta paz é um dom que recebemos quando confiamos em Cristo e seguimos Seus ensinamentos.\n\nPaulo nos ensina que esta paz guarda nossos corações e mentes. Isso significa que ela nos protege dos ataques da ansiedade, do medo e da preocupação. Quando temos a paz de Deus, mesmo em meio ao caos e às dificuldades, podemos experimentar uma serenidade interior que não faz sentido para o mundo.\n\nComo podemos receber esta paz? Através da oração, da súplica e da ação de graças. A oração é nossa forma de comunicar com Deus, expressando nossas necessidades e preocupações. A súplica é uma oração mais intensa e específica, onde clamamos a Deus por ajuda. E a ação de graças é essencial, pois nos lembra das bênçãos que já recebemos e fortalece nossa fé.\n\nA paz de Deus não elimina os problemas, mas nos dá a força e a perspectiva necessárias para enfrentá-los. Ela nos lembra que Deus está no controle e que tudo coopera para o bem daqueles que O amam.\n\nEsta paz também nos ajuda a manter o foco no que realmente importa. Em vez de nos preocuparmos com coisas que não podemos controlar, podemos confiar que Deus está trabalhando em todas as situações para o nosso bem.\n\nA paz de Deus é um sinal de maturidade espiritual. Quanto mais confiamos em Deus e mais tempo passamos em Sua presença, mais natural se torna experimentar esta paz em nossas vidas.\n\nQuando sentimos ansiedade, podemos lembrar desta promessa e buscar a paz de Deus através da oração e da confiança. Ela está sempre disponível para aqueles que a buscam com fé.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 4;

-- Capítulo 5: Não Temas, Porque Eu Sou Contigo
UPDATE bible_study_chapters 
SET reflective_reading = 'Deus nos dá uma promessa poderosa: "Não temas, porque Eu sou contigo." Esta é uma das promessas mais reconfortantes da Bíblia, pois nos lembra que nunca estamos sozinhos, não importa o que estejamos enfrentando.\n\nO medo é uma emoção natural que pode nos paralisar e impedir de viver plenamente. Mas quando confiamos em Deus, podemos superar nossos medos e viver com coragem e confiança. A presença de Deus em nossas vidas nos dá a força necessária para enfrentar qualquer desafio.\n\nDeus não promete que não teremos problemas ou dificuldades, mas promete estar conosco em meio a eles. Esta é uma diferença crucial que nos ajuda a manter a perspectiva correta. Não precisamos temer porque Deus está sempre presente, guiando e protegendo.\n\nA presença de Deus também nos dá sabedoria para tomar decisões difíceis. Quando confiamos nEle, podemos ter certeza de que Ele vai nos guiar no caminho certo, mesmo quando não conseguimos ver o que está à frente.\n\nEsta promessa nos lembra que Deus é fiel e que Sua presença é constante. Não importa se estamos em um momento de alegria ou tristeza, de sucesso ou fracasso, Deus está sempre conosco, oferecendo amor, consolo e direção.\n\nQuando sentimos medo ou ansiedade, podemos lembrar desta promessa e encontrar coragem na presença de Deus. Ele é maior que qualquer problema que possamos enfrentar e tem o poder de nos dar a paz que precisamos.\n\nA confiança em Deus nos liberta do medo e nos permite viver com mais ousadia e propósito. Sabendo que Ele está conosco, podemos enfrentar os desafios da vida com coragem e determinação.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 5;

-- Capítulo 6: O Senhor é Meu Pastor, Nada Me Faltará
UPDATE bible_study_chapters 
SET reflective_reading = 'O Salmo 23 é uma das passagens mais reconfortantes da Bíblia, pois nos lembra que Deus é nosso pastor e que Ele cuida de todas as nossas necessidades. Como um pastor cuida de suas ovelhas, Deus cuida de nós com amor, proteção e provisão.\n\nQuando confiamos em Deus como nosso pastor, podemos ter certeza de que nada nos faltará. Isso não significa que teremos tudo o que queremos, mas que teremos tudo o que precisamos para viver uma vida plena e significativa.\n\nDeus nos guia pelos caminhos da justiça, mesmo quando não conseguimos ver o caminho à frente. Ele nos leva a pastos verdejantes e águas tranquilas, proporcionando descanso e renovação para nossas almas. Mesmo quando passamos pelo vale da sombra da morte, Ele está conosco, oferecendo conforto e proteção.\n\nA vara e o cajado do pastor nos consolam, lembrando-nos de que Deus está sempre presente para nos proteger e guiar. Ele prepara uma mesa diante de nós na presença de nossos inimigos, mostrando que Sua provisão é abundante mesmo em tempos difíceis.\n\nDeus unge nossa cabeça com óleo, simbolizando Sua bênção e favor. Nosso cálice transborda, indicando que Suas bênçãos são mais do que suficientes para nossas necessidades.\n\nA bondade e a misericórdia de Deus nos seguem todos os dias de nossa vida, e habitaremos na casa do Senhor para sempre. Esta é uma promessa de presença constante e vida eterna com Deus.\n\nQuando sentimos ansiedade ou medo, podemos lembrar que Deus é nosso pastor e que Ele cuida de nós. Sua presença nos traz paz e segurança, mesmo em meio às tempestades da vida.\n\nConfiar em Deus como nosso pastor nos liberta da preocupação e nos permite viver com mais confiança e gratidão. Sabendo que Ele cuida de nós, podemos descansar em Sua provisão e seguir Seus caminhos com fé.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 6;

-- Capítulo 7: Vivendo Livre da Ansiedade
UPDATE bible_study_chapters 
SET reflective_reading = 'Viver livre da ansiedade é possível quando aplicamos os princípios bíblicos que aprendemos ao longo deste estudo. Não se trata de eliminar completamente a ansiedade de nossas vidas, mas de aprender a lidar com ela de forma saudável e bíblica.\n\nO primeiro passo é reconhecer que a ansiedade é uma emoção normal, mas não deve controlar nossas vidas. Quando sentimos ansiedade, devemos usar isso como um sinal para buscar a presença de Deus e confiar nEle.\n\nA oração regular é essencial para manter a paz interior. Devemos orar não apenas quando estamos desesperados, mas como parte de nossa rotina diária. A oração nos conecta com Deus e nos lembra de Sua presença constante.\n\nEstudar a Palavra de Deus regularmente nos fortalece e nos dá a perspectiva correta sobre a vida. As promessas de Deus nos lembram de que Ele está no controle e que podemos confiar nEle em todas as situações.\n\nManter o foco no que é eterno em vez do que é temporal nos ajuda a reduzir a ansiedade. Quando priorizamos o reino de Deus, as preocupações terrenas perdem sua força sobre nós.\n\nCultivar relacionamentos saudáveis e buscar apoio da comunidade cristã também é importante. Não devemos enfrentar nossas lutas sozinhos, mas compartilhar nossas cargas com outros crentes.\n\nPraticar a gratidão diariamente nos ajuda a manter a perspectiva correta. Mesmo em tempos difíceis, sempre há algo pelo qual agradecer, e isso nos lembra das bênçãos de Deus em nossas vidas.\n\nA liberdade da ansiedade não significa uma vida sem problemas, mas uma vida com paz interior mesmo em meio às dificuldades. É uma paz que vem de confiar em Deus e saber que Ele está sempre conosco, guiando e protegendo.\n\nQuando aplicamos estes princípios consistentemente, descobrimos que podemos viver com mais alegria, propósito e paz, independentemente das circunstâncias que enfrentamos.'
WHERE study_id = 'fc1af9d3-5510-43a5-a22a-4a30a7fc0dbd' AND chapter_number = 7; 